# Generated by Django 5.2.11 on 2026-02-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_custom_properties'),
        ('m3u', '0018_add_profile_custom_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='m3u_profiles',
            field=models.ManyToManyField(blank=True, related_name='users', to='m3u.m3uaccountprofile'),
        ),
    ]
